name: Run Node.js script on a schedule

on:
  push:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - name: Run script
        run: npm start
        env:
          SECRET_TEST_MESSAGE: ${{ secrets.SECRET_TEST_MESSAGE }}
